# Generated by Django 6.1.1 on 2026-09-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='Blog_1_post_publish_fa25e1_idx',
            old_name='Blog_1_post_publish_cf2959_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=250, unique_for_date='publish'),
        ),
    ]
